{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExpection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mac"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdk\/devicecallback\/onexpection(mac:ex:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/SDK\/documentation\/SDK\/DeviceCallback\/onExpection(mac:ex:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Функция вызывающаяся при возникновения ошибки при работе сервиса"}],"kind":"symbol","metadata":{"role":"symbol","title":"onExpection(mac:ex:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExpection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mac"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:3SDK14DeviceCallbackP11onExpection3mac2exy10Foundation4UUIDV_s5Error_ptF","required":true,"modules":[{"name":"SDK"}]},"hierarchy":{"paths":[["doc:\/\/SDK\/documentation\/SDK","doc:\/\/SDK\/documentation\/SDK\/DeviceCallback"]]},"references":{"doc://SDK/documentation/SDK":{"role":"collection","title":"SDK","abstract":[],"identifier":"doc:\/\/SDK\/documentation\/SDK","kind":"symbol","type":"topic","url":"\/documentation\/sdk"},"doc://SDK/documentation/SDK/DeviceCallback":{"role":"symbol","title":"DeviceCallback","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceCallback"}],"abstract":[{"type":"text","text":"Экземпляр для функций обратного вызова из приложения"}],"identifier":"doc:\/\/SDK\/documentation\/SDK\/DeviceCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeviceCallback"}],"url":"\/documentation\/sdk\/devicecallback"},"doc://SDK/documentation/SDK/DeviceCallback/onExpection(mac:ex:)":{"role":"symbol","title":"onExpection(mac:ex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExpection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mac"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Функция вызывающаяся при возникновения ошибки при работе сервиса"}],"identifier":"doc:\/\/SDK\/documentation\/SDK\/DeviceCallback\/onExpection(mac:ex:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdk\/devicecallback\/onexpection(mac:ex:)"}}}